version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  swift:
    username: kiwenlau:swift
    password: HMYD9mkKY9gGNa5TTZB4gUqCIgvG2hboLIZeyaR8 
    authurl: http://127.0.0.1:8080/auth/v1.0
    tenantid: kiwenlau
    insecureskipverify: false
    container: registry
    rootdirectory: /registry
http:
    addr: :6000
    debug:
        addr: localhost:6001
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
